# Creacion e indexación

1. Crea un array 1D con 50 valores aleatorios del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

In [1]:
import numpy as np

In [4]:
arr1 = np.random.randint(10, 100, (50))

In [5]:
arr1

array([88, 79, 17, 25, 87, 57, 43, 73, 29, 24, 24, 30, 23, 85, 98, 66, 80,
       36, 13, 15, 96, 67, 93, 87, 68, 48, 72, 37, 43, 46, 81, 67, 23, 97,
       56, 12, 15, 55, 27, 55, 83, 13, 82, 60, 95, 88, 98, 41, 38, 48])

In [8]:
arr1[4::5]

array([87, 24, 98, 15, 68, 46, 56, 55, 95, 48])

2. Crea un array 1D con 30 valores aleatorios del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

In [9]:
arr2 = np.random.randint(1, 21, (30))

In [10]:
arr2

array([19,  2,  5,  8,  4,  2,  8,  3, 13,  2, 17,  2, 20,  5, 11, 12,  4,
        1, 10, 11,  3, 17, 20, 14,  3,  8, 10,  5, 19,  6])

In [11]:
arr2[1::2]

array([ 2,  8,  2,  3,  2,  2,  5, 12,  1, 11, 17, 14,  8,  5,  6])


3. Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). 
    
    Accede a la última fila de la matriz. 
    
    Los decimales deben estar redondeados a 2 decimales.

In [12]:
arr3 = np.random.rand(4,6)

In [13]:
arr3

array([[0.19979168, 0.92629505, 0.08782511, 0.34792841, 0.67488793,
        0.13021963],
       [0.31911279, 0.00665164, 0.91098874, 0.50647043, 0.88252471,
        0.79566089],
       [0.04418752, 0.58106444, 0.72087778, 0.79235449, 0.89035338,
        0.67844898],
       [0.7289578 , 0.03871906, 0.91971265, 0.2746439 , 0.15346195,
        0.13190321]])

In [14]:
arr3[-1]

array([0.7289578 , 0.03871906, 0.91971265, 0.2746439 , 0.15346195,
       0.13190321])

In [15]:
red = np.round(arr3, 2)

In [16]:
red

array([[0.2 , 0.93, 0.09, 0.35, 0.67, 0.13],
       [0.32, 0.01, 0.91, 0.51, 0.88, 0.8 ],
       [0.04, 0.58, 0.72, 0.79, 0.89, 0.68],
       [0.73, 0.04, 0.92, 0.27, 0.15, 0.13]])

# Funciones aritméticas y estádisticas

1. Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

In [28]:
arr1 = np.round(np.random.rand(2, 3, 5), 1)

In [29]:
arr1

array([[[0.3, 0.1, 0.2, 0.3, 1. ],
        [0.7, 0.3, 0.1, 0.7, 0.5],
        [0.6, 0.5, 0.1, 0.3, 0.4]],

       [[0.4, 0.9, 0.9, 0.3, 0.5],
        [0.7, 0.6, 0.5, 0.3, 0.7],
        [0.8, 0.4, 0.3, 0.5, 0.9]]])

2. Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. 

    Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:

    - Si el valor del array es igual que la media, se reemplaza por "A".

    - Si el valor del array es mayor que la media, se reemplaza por "B".

    - Si el valor del array es menor que la media, se reemplaza por "C".

    - Si el valor es igual que el máximo, se reemplaza por "D".

    -  Si el valor es igual que el mínimo, se reemplaza por "E".

In [32]:
arr2 = np.round(np.empty((2,3,5), dtype=float),1)

In [41]:
masc_1 = arr1 == arr1.mean()

In [42]:
masc_2 = arr1 > arr1.mean()

In [43]:
masc_3 = arr1 < arr1.mean()

In [44]:
masc_4 = arr1 == arr1.max()

In [45]:
masc_5 = arr1 == arr1.min()

In [75]:
arr2 = np.where(masc_1, "A", arr1)

In [76]:
arr2

array([[['0.3', '0.1', '0.2', '0.3', '1.0'],
        ['0.7', '0.3', '0.1', '0.7', '0.5'],
        ['0.6', '0.5', '0.1', '0.3', '0.4']],

       [['0.4', '0.9', '0.9', '0.3', '0.5'],
        ['0.7', '0.6', '0.5', '0.3', '0.7'],
        ['0.8', '0.4', '0.3', '0.5', '0.9']]], dtype='<U32')

In [77]:
arr2 = np.where(masc_2, "B", arr2)

In [78]:
arr2

array([[['0.3', '0.1', '0.2', '0.3', 'B'],
        ['B', '0.3', '0.1', 'B', 'B'],
        ['B', 'B', '0.1', '0.3', '0.4']],

       [['0.4', 'B', 'B', '0.3', 'B'],
        ['B', 'B', 'B', '0.3', 'B'],
        ['B', '0.4', '0.3', 'B', 'B']]], dtype='<U32')

In [79]:
arr2 = np.where(masc_3, "C", arr2)

In [80]:
arr2

array([[['C', 'C', 'C', 'C', 'B'],
        ['B', 'C', 'C', 'B', 'B'],
        ['B', 'B', 'C', 'C', 'C']],

       [['C', 'B', 'B', 'C', 'B'],
        ['B', 'B', 'B', 'C', 'B'],
        ['B', 'C', 'C', 'B', 'B']]], dtype='<U32')

In [81]:
arr2 = np.where(masc_4, "D", arr2)

In [82]:
arr2

array([[['C', 'C', 'C', 'C', 'D'],
        ['B', 'C', 'C', 'B', 'B'],
        ['B', 'B', 'C', 'C', 'C']],

       [['C', 'B', 'B', 'C', 'B'],
        ['B', 'B', 'B', 'C', 'B'],
        ['B', 'C', 'C', 'B', 'B']]], dtype='<U32')

In [83]:
arr2 = np.where(masc_5, "E", arr2)

In [85]:
arr1

array([[[0.3, 0.1, 0.2, 0.3, 1. ],
        [0.7, 0.3, 0.1, 0.7, 0.5],
        [0.6, 0.5, 0.1, 0.3, 0.4]],

       [[0.4, 0.9, 0.9, 0.3, 0.5],
        [0.7, 0.6, 0.5, 0.3, 0.7],
        [0.8, 0.4, 0.3, 0.5, 0.9]]])

In [84]:
arr2

array([[['C', 'E', 'C', 'C', 'D'],
        ['B', 'C', 'E', 'B', 'B'],
        ['B', 'B', 'E', 'C', 'C']],

       [['C', 'B', 'B', 'C', 'B'],
        ['B', 'B', 'B', 'C', 'B'],
        ['B', 'C', 'C', 'B', 'B']]], dtype='<U32')

Otra forma más rápida: where anidados

In [98]:
arr2 = np.round(np.empty((2,3,5), dtype=float),1)

In [ ]:
arr3 = np.empty_like(arr1) # Otra forma de hacer lo de arriba

In [104]:
arr3

array([[[0.3, 0.1, 0.2, 0.3, 1. ],
        [0.7, 0.3, 0.1, 0.7, 0.5],
        [0.6, 0.5, 0.1, 0.3, 0.4]],

       [[0.4, 0.9, 0.9, 0.3, 0.5],
        [0.7, 0.6, 0.5, 0.3, 0.7],
        [0.8, 0.4, 0.3, 0.5, 0.9]]])

In [105]:
arr3 = np.where(masc_1, "A", np.where(masc_2, "B", np.where(masc_3, "C", np.where(masc_4, "D", np.where(masc_5, "E", arr1)))))

In [94]:
arr1

array([[[0.3, 0.1, 0.2, 0.3, 1. ],
        [0.7, 0.3, 0.1, 0.7, 0.5],
        [0.6, 0.5, 0.1, 0.3, 0.4]],

       [[0.4, 0.9, 0.9, 0.3, 0.5],
        [0.7, 0.6, 0.5, 0.3, 0.7],
        [0.8, 0.4, 0.3, 0.5, 0.9]]])

Haciéndolo así, no se evaluan las últimas condiciones (D y E), vamos a cambiar el orden:

In [106]:
arr3

array([[['C', 'C', 'C', 'C', 'B'],
        ['B', 'C', 'C', 'B', 'B'],
        ['B', 'B', 'C', 'C', 'C']],

       [['C', 'B', 'B', 'C', 'B'],
        ['B', 'B', 'B', 'C', 'B'],
        ['B', 'C', 'C', 'B', 'B']]], dtype='<U32')

In [107]:
arr4 = np.where(masc_5, "E", np.where(masc_4, "D", np.where(masc_1, "A", np.where(masc_2, "B", np.where(masc_3, "C", arr1)))))

In [108]:
arr4

array([[['C', 'E', 'C', 'C', 'D'],
        ['B', 'C', 'E', 'B', 'B'],
        ['B', 'B', 'E', 'C', 'C']],

       [['C', 'B', 'B', 'C', 'B'],
        ['B', 'B', 'B', 'C', 'B'],
        ['B', 'C', 'C', 'B', 'B']]], dtype='<U32')

In [ ]:
# Esto también se puede hacer con select

np.select(lista_condiciones, lista_opciones)

# BONUS


1. Crea un array 3D de forma (2, 3, 5) y 30 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.

In [2]:
array = np.random.randint(0, 101, (2,3,5))

In [3]:
array

array([[[70, 63,  5, 87, 73],
        [64, 50, 46, 45, 55],
        [99, 62, 81,  9, 99]],

       [[20, 38, 89, 77, 46],
        [21, 71, 68,  0, 17],
        [64,  2, 48, 18, 65]]])

In [4]:
array[::,::,2::3]

array([[[ 5],
        [46],
        [81]],

       [[89],
        [68],
        [48]]])

In [ ]:
array2 = np.where(array[::,::,2::3])

In [62]:
array.size

30

In [64]:
np.arange(array)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
array.flatten()[array.flatten()[::3]]

IndexError: index 70 is out of bounds for axis 0 with size 30

In [ ]:
# Reemplazar los elementos en posiciones múltiplos de 3 por 0
array[np.arange(array.size) % 3 == 0] = 0

print("\nArray después de reemplazar elementos en posiciones múltiplos de 3 por 0:")
print(array_3d)

array([ True])